model_list:
  - model_name: gpt-4o
    litellm_params:
      model: azure/gpt-4o-deployment
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION
  - model_name: qwen3-8b-preview
    litellm_params:
      model: openai/qwen3-8b
      api_base: os.environ/OPENAI_BASE_URL
      api_key: os.environ/OPENAI_API_KEY

litellm_settings:
  store_audit_logs: true
  drop_params: true
  num_retries: 5
  request_timeout: 600
  telemetry: false
  context_window_fallbacks:
    - {"gpt-3.5-turbo": ["gpt-3.5-turbo-large"]}
  default_team_settings:
    - team_id: team-1
      success_callback: ["langfuse"]
      failure_callback: ["langfuse"]
      langfuse_public_key: os.environ/LANGFUSE_PROJECT1_PUBLIC
      langfuse_secret: os.environ/LANGFUSE_PROJECT1_SECRET
    - team_id: team-2
      success_callback: ["langfuse"]
      failure_callback: ["langfuse"]
      langfuse_public_key: os.environ/LANGFUSE_PROJECT2_PUBLIC
      langfuse_secret: os.environ/LANGFUSE_PROJECT2_SECRET
      langfuse_host: os.environ/LANGFUSE_HOST

finetune_settings:
  - custom_llm_provider: azure
    api_base: os.environ/AZURE_API_BASE
    api_key: os.environ/AZURE_API_KEY
    api_version: os.environ/AZURE_FINETUNE_API_VERSION
  - custom_llm_provider: openai
    api_key: os.environ/OPENAI_API_KEY

files_settings:
  - custom_llm_provider: azure
    api_base: os.environ/AZURE_API_BASE
    api_key: os.environ/AZURE_API_KEY
    api_version: os.environ/AZURE_FILES_API_VERSION
  - custom_llm_provider: openai
    api_key: os.environ/OPENAI_API_KEY

router_settings:
  enable_pre_call_checks: true
  model_group_alias:
    my-special-fake-model-alias-name: fake-openai-endpoint-3

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  store_model_in_db: true
  proxy_budget_rescheduler_min_time: 60
  proxy_budget_rescheduler_max_time: 64
  proxy_batch_write_at: 1
  database_connection_pool_limit: 10

  pass_through_endpoints:
    - path: "/v1/rerank"
      target: "https://api.cohere.com/v1/rerank"
      headers:
        content-type: application/json
        accept: application/json
      forward_headers: true
